name: Update packages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_packages:
    strategy:
      matrix:
        container: 
          - archlinux:latest
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Pacman database update
        run: pacman -Syy --noconfirm
      - name: Install deps
        run: pacman -S --noconfirm git jq
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve version
        run: sh ./.github/workflows/retrieve_version.sh
      - name: Check and update current packages
        run: sh .github/workflows/update_packages.sh
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9.1.4
        id: commit
        with:
          message: "Update packages to ${{ env.release_name }}"
          add: "."
          author_name: "GitHub Actions"
          author_email: "loraner123@gmail.com"
          tag: ${{ env.tag_name }}
          tag_push: '--force'
    outputs:
      commited: ${{ steps.commit.outputs.commited }}
    
    build:
      needs: update_packages
      if: needs.update_packages.outputs.commited
      uses: ./.github/workflows/build.yml

            
    